import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "../components/sidebar/AppSidebar";
import { ThemeProvider } from "..//components/ThemeProvider";
import Header from "../components/common/Header";
import { SidebarInset, SidebarProvider } from "../components/ui/sidebar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner"
import { websiteName } from "@/lib/constants";
import { populateUser } from "@/lib/actions/user.action";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: `${websiteName} - Admin Panel`,
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await populateUser()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-gray-700 to-gray-950 w-full h-[100vh]`}
      >
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <Header />
                {
                  children
                }
                <Toaster richColors />
              </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
